### PR TITLE
Added support to CentOS 5/6 using service_style "init.d"

### PR DESCRIPTION
**Pull request by tiago-cruz-movile**
Fix https://github.com/SimpleFinance/chef-zookeeper/issues/71
- Added support to CentOS 5/6 using service_style "init.d"
- Few foodcritcs fixes (FC001 and FC019)

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@tiago-cruz-movile thanks for your contribution!

A couple of requests:

* Would you please undo the Foodcritic changes?
    * It’s appreciated, and I’m a stickler for this stuff as well, but, AFAIK, we were good with FC019, and [FC001 is depracated](http://www.foodcritic.io/#FC001).
* Would you please undo the additions to the CHANGELOG and the version number bump?
    * We might not release a new version right away, and it’s misleading to have new version numbers without an actual Supermarket release to accompany the metadata change
    * Additionally, if we did, this would be v2.8.0 (new feature, not just a bugfix), not v2.7.1

In future, I’d encourage making more, smaller commits, to ease revisions like this (e.g., each Foodcritic tweak is a commit, and the init script feature is a commit).

**Comment by jeffbyrnes** [comment]
@tiago-cruz-movile @adamb0mb would love to see this cleaned up as per my requests above, as CentOS support using SysV would be great!

**Comment by adamb0mb** [comment]
@jeffbyrnes The PR I had was basically a cleaned up version of what @tiago-cruz-movile had done, with one additional fix.
I spent a few minutes trying to create a new PR that was a cleaned up version of his, but my git-fu was not strong enough.

**Comment by jeffbyrnes** [comment]
I’ll see if I can get it sorted out next week. Buried in some other stuff today.

**Comment by adamb0mb** [comment]
:+1:

**Comment by jeffbyrnes** [comment]
Solved w/ #148

**Pull request closed without merging**
