### PR TITLE
Add support for Amazon Linux

### PR DESCRIPTION
**Pull request by neil-greenwood**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Thanks @neil-greenwood!

**Comment by jeffbyrnes** [comment]
@neil-greenwood by the way, your email address that you use to sign your commits isn’t attached to your GitHub profile, which means your commits aren’t being attributed to your account, even though they say your name.

I’d encourage two things:

1. Add this email address to your profile to pick up these commits
2. Always use your personal email address to sign commits, so your commits will always be “yours” (handy for when you eventually switch jobs)

**Comment by jeffbyrnes** [comment]
Cut v2.13.1 & pushed to Supermarket w/ a little improvement of my own :smile:

**Comment by neil-greenwood** [comment]
I have added the email address... Maybe it was after the commit though.

**Pull request merged**
