### PR TITLE
Add SysV service for stronger support for CentOS systems

### LINKED ISSUE #71: doesn't seem to auto start on centos/amazon linux
I'm running amazon linux (centos) and while Exhibitor and Zookeeper start fine if I manually execute the exec line of /etc/init/exhibitor.conf, the recipe itself hangs at 

Recipe: zookeeper::exhibitor
  * service[exhibitor] action stop (up to date)
  * service[exhibitor] action start
    - start service service[exhibitor]

for 5+ minutes before reporting a successful finish.  But, chef doesn't actually start it.  a ps shows no java running or anything for exhibitor.

issuing "start exhibitor" seems to just hang and not do anything.

### PR DESCRIPTION
**Pull request by jeffbyrnes**
* Builds on @tiago-cruz-movile & @adamb0mb’s work (thanks!)
* Fixes #71, #135, & #146

### CODE REVIEW

**Comment by adamb0mb** [comment]
There is one more issue that may crop up. It has to do with the `Chef::Provider::Service::Debian` reference in the `zookeeper:service` recipe.

You can see how I (mediocrely) handled it here: https://github.com/payscale/chef-zookeeper/blob/master/recipes/service.rb#L74-L79

**Comment by jeffbyrnes** [comment]
@adamb0mb ah! Thanks mate; that’s helpful.

**Comment by adamb0mb** [comment]
@jeffbyrnes no prob. Thanks for your work on this cookbook. It really made my life easier! LMK if there is anything else I can do.

**Comment by jeffbyrnes** [comment]
Ok, this tests well, so I think I’ll merge it in & cut a new release on Tuesday (no time to do all that right now)

**Comment by adamb0mb** [comment]
LGTM.
Thank you!

**Pull request merged**
