### PR TITLE
Add ability to configure znode ACL via node LWRP

### PR DESCRIPTION
**Pull request by Annih**
Zookeeper nodes have an ACL system not configured by the LWRP.
This PR add ability to configure these ACLs using multiples scheme (digest, world, sasl, ip, host)
It also adds authentication support to connect to zookeeper.

cc. @aboten

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@Annih oh wow, this looks great! Any chance you can add a simple test case that writes an encrypted znode using the test cookbook, and a Serverspec test that validates the znode?

**Comment by Annih** [comment]
Yep, I'll do that

**Comment by Annih** [comment]
Done! Hope it's ok for you :)
Finally I also removed the `host` scheme because it's not supported since ZK 3.2.1.

**Comment by jeffbyrnes** [comment]
Looks great. I’ll pull it down & check it out next week; at MesosCon today.

**Comment by jeffbyrnes** [comment]
Tests well, merging in!

**Comment by jeffbyrnes** [comment]
Shipped in [v2.12.0](https://github.com/SimpleFinance/chef-zookeeper/releases/tag/v2.12.0)

**Comment by Annih** [comment]
Thanks a lot @jeffbyrnes, I think the LWRP needs  a `recursive` attribute to grant ACLs to all sub nodes, but it's part of another pull request =]

Cya!

**Comment by jeffbyrnes** [comment]
@Annih I think that’d be a great improvement to this! PR is welcome if you manage to get ’round to it.

**Pull request merged**
