### PR TITLE
add java_opts attribute so that heap settings can be overridden by another cookbook

### PR DESCRIPTION
**Pull request by andrewgoktepe**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@andrewgoktepe why the closure? This seems like a great feature.

**Comment by jeffbyrnes** [comment]
Ah, I see; you can use the `node[:zookeeper][:env_vars]` attribute I added in v2.0.1 instead.

**Comment by jeffbyrnes** [comment]
Or… I just didn’t get to #144 yet, heh.

**Comment by andrewgoktepe** [comment]
Yeah, I just wanted to remove the merge commit from the PR  Thanks for merging #144 !

**Comment by jeffbyrnes** [comment]
@andrewgoktepe sure thing; love a clean history. In future, you can just `git rebase -i` on the branch, and force-push your newly cleaned-up branch; the pull request will update itself.

**Pull request closed without merging**
